src/Entity/Message.php
<?php

namespace App\Entity;

use App\Entity\Common\CreatableEntity;
use App\Entity\Common\DeletableEntity;
use App\Entity\Common\IdentifiableEntity;
use App\Entity\Common\UpdatableEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Message
 *
 * @ORM\Table(name="messages")
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 */
class Message
{
    use IdentifiableEntity;
    use CreatableEntity;
    use UpdatableEntity;
    use DeletableEntity;

    const MESSAGES_PER_PAGE = 30;
    const MAX_IMAGE_SIZE = 1000;

    /**
     * @var User $user
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="messages")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * @var string
     *
     * @ORM\Column(name="body", type="text", nullable=true)
     */
    private $body;

    /**
     * @Assert\File(maxSize="100M")
     */
    private $file;

    /**
     * @var string
     *
     * @ORM\Column(name="file_path", type="string", length=255, nullable=true)
     */
    private $filePath;

    /**
     * @var UserMessageLike[] | ArrayCollection $userLikes
     *
     * @ORM\OneToMany(targetEntity="UserMessageLike", mappedBy="message")
     */
    private $userLikes;

    /**
     * @var string $likeCount
     *
     * @ORM\Column(name="like_count", type="integer", nullable=true)
     */
    private $likeCount;

    public function __construct()
    {
        $this->userLikes = new ArrayCollection();
    }

    /**
     * Set user
     *
     * @param User $user
     * @return self
     */
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set body
     *
     * @param string $body
     * @return self
     */
    public function setBody($body)
    {
        $icons = [
            ':)'        => '☺️',
            ':-)'       => '☺️',
            ':('        => '😢',
            ':-('       => '😢',
            ';)'        => '😉',
            ';-)'       => '😉',
            ':D'        => '😀',
            ':*'        => '😘',
            ':X'        => '😘',
            ':x'        => '😘',
            '**---____' => '😏',
            '***---___' => '😏',
            '*-_'       => '😏',
            '**--__'    => '😏',
        ];

        // not using these anymore
        $longListOfIcons = [
            ':-)'       => '☺️',
            ':-('       => '😢',
            ';-)'       => '😉',
            ':-D'       => '😀',
            '8-O'       => '😳',
            ':-O'       => '😳',
            ':-0'       => '😳',
            '8-)'       => '😎',
            ':-?'       => '😕',
            ':-*'       => '😘',
            ':-P'       => '😛',
            ':-|'       => '😐',
            '}-('       => '😠',
            ':)'        => '☺️',
            ':('        => '😢',
            ';)'        => '😉',
            ':D'        => '😀',
            '8O'        => '😳',
            '8)'        => '😎',
            ':?'        => '😕',
            ':*'        => '😘',
            ':X'        => '😘',
            ':x'        => '😘',
            ':P'        => '😛',
            ';P'        => '😛',
            ':p'        => '😛',
            ';p'        => '😛',
            ':|'        => '😐',
            '}|'        => '😠',
            '**---____' => '😏',
            '***---___' => '😏',
            '*-_'       => '😏',
            '**--__'    => '😏',
        ];

        foreach ($icons as $key => $value) {
            $body = str_replace($key, $value, $body);
        }

        $this->body = $body;

        return $this;
    }

    /**
     * Get body
     *
     * @return string 
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Set filePath
     *
     * @param string $filePath
     * @return self
     */
    public function setFilePath($filePath)
    {
        $this->filePath = $filePath;

        return $this;
    }

    /**
     * Get filePath
     *
     * @return string
     */
    public function getFilePath()
    {
        return $this->filePath;
    }

    /**
     * Get all user likes for this message
     *
     * @return UserMessageLike[]|ArrayCollection
     */
    public function getUserLikes()
    {
        return $this->userLikes;
    }

    public function getUserLikesNames()
    {
        return join(", ", array_map(function($userLike) {
            return $userLike->getUser()->getUsername();
        }, $this->userLikes->toArray()));
    }

    /**
     * Add a user like for this message
     *
     * @param UserMessageLike $userMessageLike
     * @return self
     */
    public function addUserLike(UserMessageLike $userMessageLike)
    {
        $this->userLikes[] = $userMessageLike;

        return $this;
    }

    /**
     * Remove a user like for a message
     *
     * @param UserMessageLike $userMessageLike
     */
    public function removeUserLike(UserMessageLike $userMessageLike)
    {
        $this->userLikes->removeElement($userMessageLike);
    }

    public function getAbsolutePath()
    {
        return null === $this->filePath
            ? null
            : $this->getUploadRootDir().'/'.$this->filePath;
    }

    public function getWebPath()
    {
        return null === $this->filePath
            ? null
            : $this->getUploadDir().'/'.$this->filePath;
    }

    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../public/'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads/images';
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    public function upload()
    {
        // the file property can be empty if the field is not required
        if (null === $this->getFile()) {
            return;
        }

        $image = $this->getFile()->getPathname();

        $uid = uniqid('', true);
        $ext = $this->getFile()->getClientOriginalExtension();

        $filePath = sprintf("%s.%s", $uid, $ext);

        $imageDetails = getimagesize($image);
        $orientation = null;

        // get the image type
        switch ($imageDetails['mime']) {
            case 'image/pjpeg':
            case 'image/jpeg':
            case 'image/jpg':
                $exif = exif_read_data($image);
                if (isset($exif['Orientation'])) {
                    $orientation = $exif['Orientation']; // yes, that's a capital O
                }
                $originalImage = imagecreatefromjpeg($image);
                break;
            case 'image/png':
                $originalImage = imagecreatefrompng($image);
                break;
            case 'image/gif':
                $originalImage = imagecreatefromgif($image);
                break;
            case 'image/webp':
                $originalImage = imagecreatefromwebp($image);
                break;
            default:
                throw new \Exception("This file doesn't appear to be an image");
        }

        /*
            exif orientation codes from http://sylvana.net/jpegcrop/exif_orientation.html
            Value    0th Row      0th Column
            1        top          left side (normal)
            2        top          right side
            3        bottom       right side (rotated 180)
            4        bottom       left side
            5        left side    top
            6        right side   top (rotated 90)
            7        right side   bottom
            8        left side    bottom (rotated -90)
            Can't be bothered dealing with mirror images so will ignore
            (no flip functionality in GD so pixel by pixel ball-ache required to implement)
         */
        switch ($orientation) {
            case 3:
                $originalImage = imagerotate($originalImage, 180, 0);
                break;
            case 6:
                $originalImage = imagerotate($originalImage, -90, 0);
                break;
            case 8:
                $originalImage = imagerotate($originalImage, 90, 0);
                break;
        }

        $width = imagesx($originalImage);
        $height = imagesy($originalImage);

        if ($width > self::MAX_IMAGE_SIZE || $height > self::MAX_IMAGE_SIZE) {
            $scale = self::MAX_IMAGE_SIZE / max([$width, $height]);

            $newImage = imagecreatetruecolor(round($width * $scale), round($height* $scale));
            imagealphablending($newImage, false);
            imagecopyresampled(
                $newImage,
                $originalImage,
                0,
                0,
                0,
                0,
                round($width * $scale),
                round($height * $scale),
                $width,
                $height
            );
        } else {
            $newImage = $originalImage;
        }


        // save it
        switch ($imageDetails['mime']) {
            case 'image/pjpeg':
            case 'image/jpeg':
            case 'image/jpg':
                imagejpeg($newImage, $image, 75);
                break;
            case 'image/png':
                imagepng($newImage, $image);
                break;
            case 'image/gif':
                imagegif($newImage, $image);
                break;

templates/default/footer.html.twig
<div class="footer">
    <a href="{{ path('messages_all') }}" class="view-all-messages">
        {% include 'default/icon.svg.twig' with {'icon': 'all-messages'} %} View all messages
    </a>
    <a href="{{ path('rss') }}" class="rss-feed" target="_blank">
        {% include 'default/icon.svg.twig' with {'icon': 'rss'} %} RSS feed
    </a>
    <a href="#change-font-size" id="change-font-size" class="change-font-size">
        {% include 'default/icon.svg.twig' with {'icon': 'change-font-size'} %} Change font size
    </a>
    <a href="#" class="add-to-home-screen">
        {% include 'default/icon.svg.twig' with {'icon': 'add-to-home'} %} Add to home screen
    </a>
    <a href="{{ logout_path('main') }}" class="log-out">
        {% include 'default/icon.svg.twig' with {'icon': 'log-out'} %} Log out
    </a>
</div>

templates/default/header.html.twig
<div class="header">
    <a href="{{ path('homepage') }}" class="family-forum-logo">
        <svg width="30" height="30" version="1.1" viewBox="0 0 26.458 26.458" xmlns="http://www.w3.org/2000/svg">
            <g transform="translate(0 -270.54)">
                <rect y="270.54" width="26.458" height="26.458" fill="#fff" stroke-width=".051676"/>
                <g transform="matrix(.19531 0 0 .19531 -5.1676 244.16)" fill="#0e252d" aria-label="F">
                    <path d="m63.082 248.16v-90.71h62.219v21.719h-37.306v15.076h30.407v20.186h-30.407v33.729z" fill="#0e252d" stroke-width="3.194"/>
                </g>
            </g>
        </svg>
        <span>Family Forum</span>
    </a>
    <a href="{{ path('users') }}" class="view-people" title="All the people">
        {% include 'default/icon.svg.twig' with {'icon': 'people'} %} People
        {%- if hasBirthday | default(false) %} 🎂{% endif %}
    </a>
    <a href="{{ path('homepage') }}" class="view-homepage">
        {% include 'default/icon.svg.twig' with {'icon': 'messages'} %} Messages
    </a>
    <a href="#" class="show-search" title="Search">
        {% include 'default/icon.svg.twig' with {'icon': 'search'} %}
    </a>
    <form class="search-form" role="form" action="{{ path('search_by_page') }}" method="get">
        <input type="search" id="search" name="searchTerm" class="search" value="{{ searchTerm | default('') }}" placeholder="Search"/>
        <button type="submit" class="button-primary">Go</button>
    </form>
</div>

templates/default/icon.svg.twig
{# https://iconsvg.xyz/ #}
{% set icons = {
    'new-message': '<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>',
    'missing': '<path d="M14 2H6a2 2 0 0 0-2 2v16c0 1.1.9 2 2 2h12a2 2 0 0 0 2-2V8l-6-6z"/><path d="M14 3v5h5M9.9 17.1L14 13M9.9 12.9L14 17"/>',
    'search': '<circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line>',
    'context': '<line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line>>',
    'edit': '<polygon points="14 2 18 6 7 17 3 17 3 13 14 2"></polygon><line x1="3" y1="22" x2="21" y2="22"></line>',
    'bold': '<path d="M6 4h8a4 4 0 0 1 4 4 4 4 0 0 1-4 4H6z"></path><path d="M6 12h9a4 4 0 0 1 4 4 4 4 0 0 1-4 4H6z"></path>',
    'italic': '<path d="M19 4h-9M14 20H5M14.7 4.7L9.2 19.4"/>',
    'link': '<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path>',
    'image': '<rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M20.4 14.5L16 10 4 20"/>',
    'html': '<polyline points="16 18 22 12 16 6"></polyline><polyline points="8 6 2 12 8 18"></polyline>',
    'wysiwyg': '<polyline points="4 7 4 4 20 4 20 7"></polyline><line x1="9" y1="20" x2="15" y2="20"></line><line x1="12" y1="4" x2="12" y2="20"></line>',
    'thumbs-up': '<path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"></path>',
    'nav-left': '<path d="M15 18l-6-6 6-6"/>',
    'nav-right': '<path d="M9 18l6-6-6-6"/>',
    'people': '<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path>',
    'messages': '<line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line>>',
    'all-messages': '<rect x="3" y="3" width="7" height="7"></rect><rect x="14" y="3" width="7" height="7"></rect><rect x="14" y="14" width="7" height="7"></rect><rect x="3" y="14" width="7" height="7"></rect>',
    'add-image': '<g transform="translate(2 3)"><path d="M20 16a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2h3l2-3h6l2 3h3a2 2 0 0 1 2 2v11z"/><circle cx="10" cy="10" r="4"/></g>',
    'log-out': '<path d="M10 3H6a2 2 0 0 0-2 2v14c0 1.1.9 2 2 2h4M16 17l5-5-5-5M19.8 12H9"/>',
    'rss': '<path d="M4 11a9 9 0 0 1 9 9"></path><path d="M4 4a16 16 0 0 1 16 16"></path><circle cx="5" cy="19" r="1"></circle>',
    'add-to-home': '<path d="M3 3h18v18H3zM12 8v8m-4-4h8"/>',
    'change-font-size': '<polyline points="4 7 4 4 20 4 20 7"></polyline><line x1="9" y1="20" x2="15" y2="20"></line><line x1="12" y1="4" x2="12" y2="20"></line>',
} %}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
     class="icon icon-{{ icon | default('missing') }}" stroke="{{ stroke | default('currentColor') }}"
     stroke-width="{{ strokeWidth | default(2) }}" stroke-linecap="{{ strokeLinecap | default('round') }}"
     stroke-linejoin="{{ strokeLinejoin | default('round') }}" width="16" height="16">
    {{ icons[icon | default('missing')] | raw }}
</svg>

templates/default/like.html.twig
{% spaceless %}
{% if app.user == message.user %}
    {% if message.likeCount > 0 %}
        <div class="message-likes">
            <div class="like my-likes" title="Liked by {{ message.getUserLikesNames() }}">
                {% include 'default/icon.svg.twig' with {'icon': 'thumbs-up'} %}
                <span class="like-count">{{ message.likeCount }}</span>
            </div>
        </div>
    {% endif %}
{% else %}
    <div class="message-likes">
        <a href="{{ path('like_message', {'id' : message.id}) }}"
            {%- if app.user and message.isLikedByUser(app.user) %} class="like liked"{% else %} class="like"{% endif -%}
            {%- if message.likeCount > 0 %} title="Liked by {{ message.getUserLikesNames() }}"
            {%- else %} title="Like this"{% endif %}>
            {% include 'default/icon.svg.twig' with {'icon': 'thumbs-up'} %}
            {%- if message.likeCount > 0 %}<span class="like-count">{{ message.likeCount }}</span>{% endif -%}
        </a>
    </div>
{% endif %}
{% endspaceless %}

templates/default/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | Login{% endblock %}
{% block bodyClasses %}{{ parent() }} page-login{% endblock %}

{% block stylesheets -%}
    {{ parent() }}
    <style type="text/css">
        .login-form-area {
            display: grid;
            justify-content: center;
            align-items: center;
        }

        .login-form-area form {
            color: var(--message-color);
            background-color: var(--message-bg-color);
            box-shadow: 2px 2px 2px rgba(69, 18, 0, 0.1);
            border-left: var(--message-border-size) solid var(--default-message-border-color);
            border-top-left-radius: var(--message-border-size);
            border-bottom-left-radius: var(--message-border-size);
            padding: var(--gap);
            display: grid;
            grid-gap: var(--gap-small);
        }

        .login-form-area button {
            justify-self: self-start;
        }

        .page-login .header {
            grid-template-columns: 1fr;
            grid-template-rows: 1fr;
            justify-items: center;
        }
    </style>
{% endblock -%}

{% block header %}
    <div class="header">
        <span class="family-forum-logo">Family Forum</span>
    </div>
{% endblock header %}

{% block main %}
    <section class="main login-form-area">
        <form name="login" method="post" action="{{ path('login_check') }}" role="form" class="card">
            {% if error %}
                <div class="alert alert-info">{{ error }}</div>
            {% endif %}
            <div class="form-group">
                <label class="control-label required" for="login_username">Name</label>
                <input type="text" id="login_username" name="_username" required="required" autofocus
                       class="form-control" value="{{ last_username | default('') }}">
            </div>
            <div class="form-group">
                <label class="control-label required" for="login_password">Password</label>
                <input type="password" id="login_password" name="_password" required="required" class="form-control">
            </div>
            <div class="form-group checkbox">
                <input type="checkbox" id="login_remember_me" name="_remember_me" value="1" checked>
                <label for="login_remember_me">Remember me</label>
            </div>
            <button type="submit" class="button-primary">Login</button>
        </form>
    </section>
{% endblock %}

{% block footer %}
{% endblock %}

{% block javascripts -%}
{% endblock %}

templates/default/messageCreate.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | Create message{% endblock %}
{% block bodyClasses %}{{ parent() }} page-message-create{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/messages.css', 'css') }}">
{% endblock %}

{% block main %}
    <section class="main messages {% if message is defined and message.filePath -%}has-image{% endif %}">
        {% include 'default/messageForm.html.twig' with {'message' : message, 'showDelete' : false} %}
        {%- for message in messages -%}
            {%- include 'default/message.html.twig' %}
        {% endfor %}
    </section>
{% endblock %}

{% block javascripts -%}
    {{ parent() }}
    <script type="module" src="{{ asset('js/editor.js', 'js') }}"></script>
{% endblock %}

templates/default/messageEdit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | Edit message{% endblock %}
{% block bodyClasses %}{{ parent() }} page-message-edit{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/messages.css', 'css') }}">
{% endblock %}

{% block main %}
    <section class="main {% if message is defined and message.filePath -%}has-image{% endif %}">
        {% include 'default/messageForm.html.twig' with {'message' : message, 'showDelete' : true} %}
    </section>
{% endblock %}

{% block javascripts -%}
    {{ parent() }}
    <script type="module" src="{{ asset('js/editor.js', 'js') }}"></script>
{% endblock %}

templates/default/messageForm.html.twig
{{ form_start(
    form, {
        'attr': {
            'class': 'card message-form ' ~ extraClasses | default(''),
            'style': 'border-left-color:' ~ app.user.color | default('var(--default-message-color)')
        }
    })
}}
<div class="uploaded-image message-image{% if message is not defined or not message.webPath %} is-hidden{% endif %}">
    <img src="{% if message is defined and message.webPath %} {{ asset(message.webPath) }}{% endif %}" alt="Current photo"/>
    <a href="#" class="remove-image button button-warning">Remove photo</a>
</div>
<div class="form-fields">
    <div class="form-group photo-form-group{% if message is defined and message.webPath %} is-hidden{% endif %}">
        {{ form_widget(form.file, {'attr': {'class': 'image-file-name'}}) }}
        <span class="button button-primary upload-photo" title="Upload photo">
            {% include 'default/icon.svg.twig' with {'icon': 'add-image', 'stroke': '#FFFFFF'} %} Upload photo
        </span>
    </div>
    <div class="form-group">
        {{ form_label(form.body, 'Your message') }}
        <div id="message-editor"></div>
        <div id="back-to-editor" class="pell-actionbar is-hidden">
            <button class="pell-button" title="What you see is what you get">
                {% include 'default/icon.svg.twig' with {'icon': 'wysiwyg'} %}&nbsp;WYSIWYG
            </button>
        </div>
        {{ form_widget(form.body, {'attr' : {'class' : 'is-hidden'}}) }}
        {{ form_errors(form.body) }}
    </div>
    {% if form.isBrenter is defined %}
        <div class="form-group checkbox">
            {{ form_widget(form.isBrenter) }}
            {{ form_label(form.isBrenter) }}
            {{ form_errors(form.isBrenter) }}
        </div>
    {% endif %}
    {{ form_row(form.filePath, {'attr' : {'class' : 'image-path'}}) }}
    {{ form_rest(form) }}
    <div class="form-actions">
        <button type="submit" class="message-save button button-primary">Save</button>
        <a href="{{ path('messages') }}" class="message-cancel-edit button button-warning">Cancel</a>
        {% if showDelete | default(false) %}
            <a href="{{ path('message_delete', {'id' : message.id}) }}" class="message-delete button button-danger">Delete</a>
        {% endif %}
    </div>
</div>
{{ form_end(form) }}

templates/default/messages.html.twig
{% extends 'base.html.twig' %}

{% block head %}
    {% if app.user and app.user.id in [3] %}
        <link rel="prefetch" href="{{ path('users') }}">
        {% if page < pagesCount %}
            <link rel="next" href="{{ nextLink }}">
        {% endif %}
    {% endif %}
{% endblock %}

{% block bodyClasses %}{{ parent() }} page-messages{% if page == 1 %} homepage{% endif %}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/messages.css', 'css') }}">
{% endblock %}

{% block main -%}
    <section class="main messages">
    <a href="{{ path('message_create') }}" class="button button-primary message-create-new">
        {% include 'default/icon.svg.twig' with {'icon': 'new-message'} %} Create a new message</a>
    {%- if messages | length > 0 -%}
        {%- include 'default/pagination.html.twig' with {'extraClasses' : 'pagination-top'} -%}
    {%- endif -%}
    {%- if messages | length > 0 -%}
        {%- for message in messages -%}
            {%- include 'default/message.html.twig' %}
        {% endfor %}
    {% else %}
        <div class="alert alert-info">Sorry, there aren't any messages to see here.</div>
    {% endif %}
    {%- if messages | length > 0 -%}
        {%- include 'default/pagination.html.twig' with {'extraClasses' : 'pagination-bottom'} -%}
    {%- endif -%}
</section>
{% endblock -%}

{% block javascripts -%}
    {{ parent() }}
    <script type="module" src="{{ asset('js/messages.js', 'js') }}"></script>
{% endblock %}

templates/default/messages.xml.twig
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:media="http://search.yahoo.com/mrss/" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
    <channel>
        <title>Family Forum</title>
        <link></link>
        <description>A summary of the 50 most recent posts</description>
        <language>en-nz</language>
        <pubDate>{{ 'now' | date('r') }}</pubDate>
{% if messages | length > 0 %}
    {% for message in messages %}
        <item>
            <title>Message from {{ message.user.username }} on {{ message.createdAt | date('Y-m-d') }}</title>
            <link>{{ absolute_url(path('message_context', {'id': message.id})) }}</link>
            <description>
                {{- message.body | striptags | slice(0, 140) -}}
                {%- if message.body | striptags | length > 140 %}...{% endif -%}
            </description>
            <pubDate>{{ message.createdAt | date('r') }}</pubDate>
            {% if message.filePath %}
                <media:content url="{{ absolute_url(asset(message.webPath, 'images')) }}" medium="image" type="image/jpeg" />
            {% endif %}
        </item>
    {% endfor %}
{% endif %}
    </channel>
</rss>

templates/default/pagination.html.twig
<div class="pagination{% if extraClasses %} {{ extraClasses }}{% endif %}">
    {% if page > 1 %}
        <a href="{{ prevLink }}" class="previous-page" title="Previous page">
            {% include 'default/icon.svg.twig' with {'icon': 'nav-left'} %}Prev
        </a>
    {% endif %}
    <span class="pages">Page {{ page }} of {{ pagesCount }}</span>
    {% if page < pagesCount %}
        <a href="{{ nextLink }}" class="next-page" title="Next page">
            Next{% include 'default/icon.svg.twig' with {'icon': 'nav-right'} %}
        </a>
    {% endif %}
</div>

templates/default/user.html.twig
<div class="card user user-{{ user.id }}" style="border-left-color: {{ user.color }};">
    <div class="user-heading">
        <div class="user-name">{{ user.username }}</div>
        <div class="user-birthday">{{ user.bornAt | date('j F Y') }}</div>
    </div>
    <div class="user-details">
        <dl>
            <dt>Address</dt>
            <dd>{{ user.address | nl2br }}</dd>
            {% if user.email %}
                <dt>Email</dt>
                <dd><a href="mailto:{{ user.email }}">{{ user.email }}</a></dd>
            {% endif %}
            {% if user.phoneMobile %}
                <dt>Mobile</dt>
                <dd><a href="tel:{{ user.phoneMobile }}">{{ user.phoneMobile }}</a></dd>
            {% endif %}
            {% if user.phoneHome %}
                <dt>Home</dt>
                <dd><a href="tel:{{ user.phoneHome }}">{{ user.phoneHome }}</a></dd>
            {% endif %}
            {% if user.phoneWork %}
                <dt>Work</dt>
                <dd><a href="tel:{{ user.phoneWork }}">{{ user.phoneWork }}</a></dd>
            {% endif %}
            {% if user.messageCount %}
                <dt>Messages</dt>
                <dd>{{ user.messageCount }} - <a href="{{ path('messages_by_person', {'id' : user.id}) }}">view</a></dd>
            {% endif %}
            {% if user.visitedAt %}
                <dt>Last seen</dt>
                <dd>{{ user.visitedAt | date('j M Y \\a\\t H:i', app.user.timezone) }}</dd>
            {% endif %}
        </dl>
        {% if app.user == user %}
            <a href="{{ path('user_edit', {'id' : user.id}) }}" class="button button-primary edit-my-details">
                {% include 'default/icon.svg.twig' with {'icon': 'edit'} %} Edit
            </a>
        {% endif %}
    </div>
</div>